//==============================================================================
// HFB3
// Copyright CEA, DAM F-91297 Arpajon, France
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//==============================================================================

/** \file
 *  \brief Test suite for the MultipoleOperators class.
 */

#include "gtest/gtest.h"
#include "multipole_operators.h"
#include "maxima_targets2.h"

//==============================================================================

TEST(MultipoleOperators, calcRnRecouv)
{

#define TEST_RNODD(T, A) { IVEC arg = {A}; INT k = arg(0); INT ma = arg(1); INT na = arg(2); INT mb = arg(3); INT nb = arg(4); ASSERT_NEAR(multipoleOperators.matRkn(k)(state.basis.HOqn.find({ma, na, 0, 0, 0}), state.basis.HOqn.find({mb, nb, 0, 0, 0})), T, err);}

#ifdef MULTIPOLE_OPERATORS_RNODD
  {
    double err = 1e-03;

    State state(MULTIPOLE_OPERATORS_RNODD_STATE);
    MultipoleOperators multipoleOperators(state);
    multipoleOperators.calcRkn();

    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_00_TARGET, MULTIPOLE_OPERATORS_RNODD_00_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_01_TARGET, MULTIPOLE_OPERATORS_RNODD_01_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_02_TARGET, MULTIPOLE_OPERATORS_RNODD_02_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_03_TARGET, MULTIPOLE_OPERATORS_RNODD_03_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_04_TARGET, MULTIPOLE_OPERATORS_RNODD_04_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_05_TARGET, MULTIPOLE_OPERATORS_RNODD_05_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_06_TARGET, MULTIPOLE_OPERATORS_RNODD_06_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_07_TARGET, MULTIPOLE_OPERATORS_RNODD_07_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_08_TARGET, MULTIPOLE_OPERATORS_RNODD_08_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_09_TARGET, MULTIPOLE_OPERATORS_RNODD_09_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_10_TARGET, MULTIPOLE_OPERATORS_RNODD_10_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_11_TARGET, MULTIPOLE_OPERATORS_RNODD_11_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_12_TARGET, MULTIPOLE_OPERATORS_RNODD_12_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_13_TARGET, MULTIPOLE_OPERATORS_RNODD_13_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_14_TARGET, MULTIPOLE_OPERATORS_RNODD_14_ARG0);
    TEST_RNODD(MULTIPOLE_OPERATORS_RNODD_15_TARGET, MULTIPOLE_OPERATORS_RNODD_15_ARG0);
  }
#endif

}

//==============================================================================
//==============================================================================
//==============================================================================

TEST(MultipoleOperators, calcQlmHO)
{

#define TEST_QLMHO(T, LM, A, B) ASSERT_NEAR(multipoleOperators.qlmHO(LM)(state.basis.HOqn.find({A}), state.basis.HOqn.find({B})), T, err);

#ifdef MULTIPOLE_OPERATORS_QLMHO_1CT
  {
    double err = 1e-07;

    State state(MULTIPOLE_OPERATORS_QLMHO_1CT_STATE);
    MultipoleOperators multipoleOperators(state);
    multipoleOperators.calcRkn();

    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_00_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_00_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_00_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_00_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_01_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_01_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_01_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_01_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_02_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_02_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_02_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_02_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_03_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_03_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_03_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_03_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_04_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_04_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_04_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_04_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_05_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_05_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_05_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_05_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_06_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_06_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_06_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_06_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_07_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_07_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_07_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_07_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_08_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_08_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_08_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_08_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_09_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_09_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_09_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_09_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_10_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_10_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_10_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_10_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_11_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_11_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_11_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_11_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_12_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_12_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_12_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_12_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_13_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_13_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_13_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_13_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_14_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_14_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_14_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_14_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_15_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_15_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_15_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_15_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_16_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_16_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_16_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_16_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_17_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_17_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_17_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_17_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_18_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_18_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_18_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_18_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_19_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_19_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_19_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_19_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_20_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_20_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_20_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_20_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_21_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_21_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_21_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_21_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_22_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_22_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_22_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_22_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_23_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_23_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_23_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_23_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_24_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_24_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_24_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_24_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_25_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_25_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_25_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_25_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_26_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_26_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_26_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_26_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_27_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_27_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_27_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_27_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_28_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_28_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_28_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_28_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_29_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_29_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_29_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_29_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_30_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_30_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_30_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_30_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_31_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_31_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_31_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_31_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_32_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_32_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_32_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_32_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_33_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_33_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_33_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_33_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_34_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_34_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_34_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_34_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_35_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_35_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_35_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_35_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_36_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_36_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_36_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_36_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_37_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_37_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_37_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_37_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_38_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_38_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_38_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_38_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_39_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_39_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_39_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_39_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_40_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_40_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_40_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_40_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_41_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_41_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_41_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_41_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_42_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_42_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_42_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_42_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_43_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_43_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_43_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_43_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_44_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_44_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_44_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_44_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_45_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_45_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_45_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_45_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_46_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_46_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_46_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_46_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_47_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_47_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_47_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_47_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_48_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_48_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_48_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_48_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_49_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_49_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_49_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_49_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_50_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_50_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_50_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_50_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_51_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_51_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_51_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_51_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_52_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_52_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_52_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_52_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_53_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_53_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_53_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_53_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_54_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_54_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_54_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_54_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_55_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_55_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_55_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_55_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_56_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_56_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_56_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_56_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_57_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_57_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_57_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_57_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_58_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_58_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_58_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_58_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_59_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_59_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_59_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_59_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_60_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_60_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_60_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_60_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_61_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_61_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_61_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_61_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_62_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_62_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_62_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_62_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_63_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_63_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_63_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_63_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_64_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_64_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_64_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_64_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_65_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_65_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_65_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_65_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_66_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_66_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_66_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_66_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_67_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_67_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_67_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_67_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_68_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_68_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_68_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_68_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_69_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_69_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_69_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_69_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_70_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_70_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_70_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_70_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_71_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_71_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_71_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_71_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_72_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_72_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_72_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_72_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_73_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_73_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_73_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_73_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_74_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_74_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_74_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_74_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_75_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_75_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_75_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_75_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_76_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_76_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_76_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_76_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_77_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_77_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_77_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_77_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_78_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_78_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_78_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_78_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_79_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_79_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_79_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_79_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_80_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_80_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_80_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_80_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_81_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_81_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_81_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_81_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_82_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_82_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_82_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_82_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_83_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_83_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_83_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_83_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_84_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_84_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_84_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_84_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_85_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_85_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_85_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_85_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_86_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_86_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_86_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_86_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_1CT_87_TARGET, MULTIPOLE_OPERATORS_QLMHO_1CT_87_ARG0, MULTIPOLE_OPERATORS_QLMHO_1CT_87_ARG1, MULTIPOLE_OPERATORS_QLMHO_1CT_87_ARG2);
  }
#endif

#ifdef MULTIPOLE_OPERATORS_QLMHO_2CT
  {
    double err = 1e-07;

    State state(MULTIPOLE_OPERATORS_QLMHO_2CT_STATE);
    MultipoleOperators multipoleOperators(state);

    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_00_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_00_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_00_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_00_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_01_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_01_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_01_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_01_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_02_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_02_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_02_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_02_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_03_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_03_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_03_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_03_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_04_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_04_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_04_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_04_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_05_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_05_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_05_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_05_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_06_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_06_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_06_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_06_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_07_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_07_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_07_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_07_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_08_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_08_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_08_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_08_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_09_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_09_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_09_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_09_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_10_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_10_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_10_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_10_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_11_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_11_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_11_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_11_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_12_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_12_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_12_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_12_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_13_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_13_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_13_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_13_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_14_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_14_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_14_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_14_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_15_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_15_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_15_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_15_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_16_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_16_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_16_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_16_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_17_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_17_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_17_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_17_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_18_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_18_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_18_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_18_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_19_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_19_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_19_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_19_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_20_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_20_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_20_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_20_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_21_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_21_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_21_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_21_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_22_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_22_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_22_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_22_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_23_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_23_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_23_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_23_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_24_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_24_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_24_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_24_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_25_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_25_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_25_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_25_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_26_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_26_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_26_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_26_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_27_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_27_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_27_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_27_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_28_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_28_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_28_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_28_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_29_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_29_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_29_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_29_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_30_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_30_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_30_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_30_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_31_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_31_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_31_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_31_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_32_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_32_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_32_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_32_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_33_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_33_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_33_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_33_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_34_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_34_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_34_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_34_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_35_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_35_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_35_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_35_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_36_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_36_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_36_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_36_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_37_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_37_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_37_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_37_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_38_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_38_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_38_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_38_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_39_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_39_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_39_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_39_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_40_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_40_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_40_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_40_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_41_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_41_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_41_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_41_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_42_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_42_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_42_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_42_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_43_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_43_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_43_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_43_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_44_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_44_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_44_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_44_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_45_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_45_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_45_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_45_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_46_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_46_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_46_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_46_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_47_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_47_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_47_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_47_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_48_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_48_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_48_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_48_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_49_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_49_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_49_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_49_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_50_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_50_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_50_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_50_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_51_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_51_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_51_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_51_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_52_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_52_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_52_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_52_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_53_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_53_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_53_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_53_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_54_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_54_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_54_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_54_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_55_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_55_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_55_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_55_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_56_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_56_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_56_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_56_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_57_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_57_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_57_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_57_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_58_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_58_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_58_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_58_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_59_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_59_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_59_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_59_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_60_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_60_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_60_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_60_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_61_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_61_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_61_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_61_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_62_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_62_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_62_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_62_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_63_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_63_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_63_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_63_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_64_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_64_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_64_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_64_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_65_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_65_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_65_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_65_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_66_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_66_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_66_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_66_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_67_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_67_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_67_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_67_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_68_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_68_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_68_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_68_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_69_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_69_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_69_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_69_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_70_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_70_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_70_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_70_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_71_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_71_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_71_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_71_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_72_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_72_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_72_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_72_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_73_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_73_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_73_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_73_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_74_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_74_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_74_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_74_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_75_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_75_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_75_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_75_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_76_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_76_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_76_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_76_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_77_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_77_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_77_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_77_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_78_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_78_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_78_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_78_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_79_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_79_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_79_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_79_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_80_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_80_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_80_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_80_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_81_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_81_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_81_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_81_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_82_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_82_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_82_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_82_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_83_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_83_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_83_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_83_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_84_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_84_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_84_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_84_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_85_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_85_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_85_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_85_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_86_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_86_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_86_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_86_ARG2);
    TEST_QLMHO(MULTIPOLE_OPERATORS_QLMHO_2CT_87_TARGET, MULTIPOLE_OPERATORS_QLMHO_2CT_87_ARG0, MULTIPOLE_OPERATORS_QLMHO_2CT_87_ARG1, MULTIPOLE_OPERATORS_QLMHO_2CT_87_ARG2);
  }
#endif
}

// //==============================================================================
//
// TEST(MultipoleOperators, calcQl0Matrices)
// {
//   {
//     State state("examples/42Ca_deformed_1x11.msg.gz");
//     MultipoleOperators multipoleOperators(state);
//
//     double err = 1e-09;
//
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_1CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_1CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_1CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 2, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_1CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_1CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_1CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 6, 0, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_1CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_1CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_1CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_1CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 2, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_1CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_1CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_1CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 6, 0, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_1CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_1CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_1CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_1CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 2, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_1CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_1CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_1CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 6, 0, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_1CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_1CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_1CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_1CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 2, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_1CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_1CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_1CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 6, 0, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_1CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_1CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_1CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_1CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 2, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_1CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_1CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_1CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 6, 0, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_1CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_1CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_1CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_1CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 2, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_1CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_1CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_1CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 6, 0, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_1CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_1CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_1CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_1CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 2, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_1CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_1CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_1CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 6, 0, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_1CT_TARGET06, err);
//
//     //==========================================================================
//     //==========================================================================
//     //==========================================================================
//
//     ASSERT_NEAR(multipoleOperators.matR2k(1)(state.basis.HOqn.find({0, 1, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_R2RECOUV_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(1)(state.basis.HOqn.find({1, 3, 0, 0, 0}), state.basis.HOqn.find({1, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_R2RECOUV_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(1)(state.basis.HOqn.find({1, 0, 0, 0, 0}), state.basis.HOqn.find({1, 1, 0, 0, 0})), MULTIPOLE_OPERATORS_R2RECOUV_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(1)(state.basis.HOqn.find({2, 1, 0, 0, 0}), state.basis.HOqn.find({2, 3, 0, 0, 0})), MULTIPOLE_OPERATORS_R2RECOUV_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(1)(state.basis.HOqn.find({3, 2, 0, 0, 0}), state.basis.HOqn.find({3, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_R2RECOUV_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(1)(state.basis.HOqn.find({4, 0, 0, 0, 0}), state.basis.HOqn.find({4, 1, 0, 0, 0})), MULTIPOLE_OPERATORS_R2RECOUV_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(1)(state.basis.HOqn.find({6, 2, 0, 0, 0}), state.basis.HOqn.find({6, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_R2RECOUV_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matR2k(2)(state.basis.HOqn.find({0, 1, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_R4RECOUV_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(2)(state.basis.HOqn.find({1, 3, 0, 0, 0}), state.basis.HOqn.find({1, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_R4RECOUV_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(2)(state.basis.HOqn.find({1, 0, 0, 0, 0}), state.basis.HOqn.find({1, 1, 0, 0, 0})), MULTIPOLE_OPERATORS_R4RECOUV_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(2)(state.basis.HOqn.find({2, 1, 0, 0, 0}), state.basis.HOqn.find({2, 3, 0, 0, 0})), MULTIPOLE_OPERATORS_R4RECOUV_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(2)(state.basis.HOqn.find({3, 2, 0, 0, 0}), state.basis.HOqn.find({3, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_R4RECOUV_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(2)(state.basis.HOqn.find({4, 0, 0, 0, 0}), state.basis.HOqn.find({4, 1, 0, 0, 0})), MULTIPOLE_OPERATORS_R4RECOUV_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(2)(state.basis.HOqn.find({6, 2, 0, 0, 0}), state.basis.HOqn.find({6, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_R4RECOUV_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matR2k(3)(state.basis.HOqn.find({0, 1, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_R6RECOUV_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(3)(state.basis.HOqn.find({1, 3, 0, 0, 0}), state.basis.HOqn.find({1, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_R6RECOUV_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(3)(state.basis.HOqn.find({1, 0, 0, 0, 0}), state.basis.HOqn.find({1, 1, 0, 0, 0})), MULTIPOLE_OPERATORS_R6RECOUV_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(3)(state.basis.HOqn.find({2, 1, 0, 0, 0}), state.basis.HOqn.find({2, 3, 0, 0, 0})), MULTIPOLE_OPERATORS_R6RECOUV_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(3)(state.basis.HOqn.find({3, 2, 0, 0, 0}), state.basis.HOqn.find({3, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_R6RECOUV_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(3)(state.basis.HOqn.find({4, 0, 0, 0, 0}), state.basis.HOqn.find({4, 1, 0, 0, 0})), MULTIPOLE_OPERATORS_R6RECOUV_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matR2k(3)(state.basis.HOqn.find({6, 2, 0, 0, 0}), state.basis.HOqn.find({6, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_R6RECOUV_TARGET06, err);
//
//     //==========================================================================
//     //==========================================================================
//     //==========================================================================
//
//     double err = 1e-09;
//
//     State state(MULTIPOLE_OPERATORS_Q22HO_STATE);
//     MultipoleOperators multipoleOperators(state);
//
//     #define TEST_Q22HO(T, A, B) ASSERT_NEAR(multipoleOperators.qlmHO(2, 2)(state.basis.HOqn.find({A}), state.basis.HOqn.find({B})), T, err);
//
//     TEST_Q22HO(MULTIPOLE_OPERATORS_Q22HO_00_TARGET, MULTIPOLE_OPERATORS_Q22HO_00_ARG0, MULTIPOLE_OPERATORS_Q22HO_00_ARG1);
//     TEST_Q22HO(MULTIPOLE_OPERATORS_Q22HO_01_TARGET, MULTIPOLE_OPERATORS_Q22HO_01_ARG0, MULTIPOLE_OPERATORS_Q22HO_01_ARG1);
//
//
//     // ASSERT_NEAR(multipoleOperators.qlmHO(2, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 1, 9, 0, 0})), MULTIPOLE_OPERATORS_Q20HO_TARGET00, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(2, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_Q20HO_TARGET01, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(2, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Q20HO_TARGET02, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(2, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 2, 0, 0})), MULTIPOLE_OPERATORS_Q20HO_TARGET03, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(2, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 2, 0, 0})), MULTIPOLE_OPERATORS_Q20HO_TARGET04, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(2, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 3, 0, 0})), MULTIPOLE_OPERATORS_Q20HO_TARGET05, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(2, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 5, 0, 0})), MULTIPOLE_OPERATORS_Q20HO_TARGET06, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(2, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 6, 0, 0})), MULTIPOLE_OPERATORS_Q20HO_TARGET07, err);
//     //
//     // ASSERT_NEAR(multipoleOperators.qlmHO(3, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 1, 9, 0, 0})), MULTIPOLE_OPERATORS_Q30HO_TARGET00, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(3, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_Q30HO_TARGET01, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(3, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Q30HO_TARGET02, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(3, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 2, 0, 0})), MULTIPOLE_OPERATORS_Q30HO_TARGET03, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(3, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 2, 0, 0})), MULTIPOLE_OPERATORS_Q30HO_TARGET04, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(3, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 3, 0, 0})), MULTIPOLE_OPERATORS_Q30HO_TARGET05, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(3, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 5, 0, 0})), MULTIPOLE_OPERATORS_Q30HO_TARGET06, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(3, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 6, 0, 0})), MULTIPOLE_OPERATORS_Q30HO_TARGET07, err);
//     //
//     // ASSERT_NEAR(multipoleOperators.qlmHO(4, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 1, 9, 0, 0})), MULTIPOLE_OPERATORS_Q40HO_TARGET00, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(4, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_Q40HO_TARGET01, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(4, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Q40HO_TARGET02, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(4, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 2, 0, 0})), MULTIPOLE_OPERATORS_Q40HO_TARGET03, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(4, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 2, 0, 0})), MULTIPOLE_OPERATORS_Q40HO_TARGET04, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(4, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 3, 0, 0})), MULTIPOLE_OPERATORS_Q40HO_TARGET05, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(4, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 5, 0, 0})), MULTIPOLE_OPERATORS_Q40HO_TARGET06, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(4, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 6, 0, 0})), MULTIPOLE_OPERATORS_Q40HO_TARGET07, err);
//     //
//     // ASSERT_NEAR(multipoleOperators.qlmHO(5, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 1, 9, 0, 0})), MULTIPOLE_OPERATORS_Q50HO_TARGET00, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(5, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_Q50HO_TARGET01, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(5, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Q50HO_TARGET02, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(5, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 2, 0, 0})), MULTIPOLE_OPERATORS_Q50HO_TARGET03, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(5, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 2, 0, 0})), MULTIPOLE_OPERATORS_Q50HO_TARGET04, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(5, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 3, 0, 0})), MULTIPOLE_OPERATORS_Q50HO_TARGET05, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(5, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 5, 0, 0})), MULTIPOLE_OPERATORS_Q50HO_TARGET06, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(5, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 6, 0, 0})), MULTIPOLE_OPERATORS_Q50HO_TARGET07, err);
//     //
//     // ASSERT_NEAR(multipoleOperators.qlmHO(6, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 1, 9, 0, 0})), MULTIPOLE_OPERATORS_Q60HO_TARGET00, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(6, 0)(state.basis.HOqn.find({0, 1, 8, 0, 0}), state.basis.HOqn.find({0, 2, 0, 0, 0})), MULTIPOLE_OPERATORS_Q60HO_TARGET01, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(6, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 1, 0, 0})), MULTIPOLE_OPERATORS_Q60HO_TARGET02, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(6, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 0, 2, 0, 0})), MULTIPOLE_OPERATORS_Q60HO_TARGET03, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(6, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 2, 0, 0})), MULTIPOLE_OPERATORS_Q60HO_TARGET04, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(6, 0)(state.basis.HOqn.find({1, 3, 1, 0, 0}), state.basis.HOqn.find({1, 3, 3, 0, 0})), MULTIPOLE_OPERATORS_Q60HO_TARGET05, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(6, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 5, 0, 0})), MULTIPOLE_OPERATORS_Q60HO_TARGET06, err);
//     // ASSERT_NEAR(multipoleOperators.qlmHO(6, 0)(state.basis.HOqn.find({2, 1, 2, 0, 0}), state.basis.HOqn.find({2, 1, 6, 0, 0})), MULTIPOLE_OPERATORS_Q60HO_TARGET07, err);
//   }
//
//   {
//     State state("examples/42Ca_deformed_2x9.msg.gz");
//     MultipoleOperators multipoleOperators(state);
//
//     double err = 2e-09;
//
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_2CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 1, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_2CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 1, 1, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_2CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 2, 1, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_2CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_2CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_2CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(0)(state.basis.HOqn.find({0, 0, 6, 1, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z0RECOUV_2CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_2CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 1, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_2CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 1, 1, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_2CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 2, 1, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_2CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_2CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_2CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(1)(state.basis.HOqn.find({0, 0, 6, 1, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z1RECOUV_2CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_2CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 1, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_2CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 1, 1, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_2CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 2, 1, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_2CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_2CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_2CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(2)(state.basis.HOqn.find({0, 0, 6, 1, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z2RECOUV_2CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_2CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 1, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_2CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 1, 1, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_2CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 2, 1, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_2CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_2CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_2CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(3)(state.basis.HOqn.find({0, 0, 6, 1, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z3RECOUV_2CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_2CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 1, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_2CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 1, 1, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_2CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 2, 1, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_2CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_2CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_2CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(4)(state.basis.HOqn.find({0, 0, 6, 1, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z4RECOUV_2CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_2CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 1, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_2CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 1, 1, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_2CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 2, 1, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_2CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_2CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_2CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(5)(state.basis.HOqn.find({0, 0, 6, 1, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z5RECOUV_2CT_TARGET06, err);
//
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 0, 0, 0}), state.basis.HOqn.find({0, 0, 0, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_2CT_TARGET00, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 1, 0, 0}), state.basis.HOqn.find({0, 0, 1, 1, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_2CT_TARGET01, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 1, 1, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_2CT_TARGET02, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 2, 1, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_2CT_TARGET03, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 3, 0, 0}), state.basis.HOqn.find({0, 0, 4, 1, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_2CT_TARGET04, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 4, 0, 0}), state.basis.HOqn.find({0, 0, 3, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_2CT_TARGET05, err);
//     ASSERT_NEAR(multipoleOperators.matZk(6)(state.basis.HOqn.find({0, 0, 6, 1, 0}), state.basis.HOqn.find({0, 0, 7, 0, 0})), MULTIPOLE_OPERATORS_Z6RECOUV_2CT_TARGET06, err);
//   }
// }
//
// //==============================================================================
//
// TEST(MultipoleOperators, MultipoleOperators)
// {
//   {
//     // 1ct state
//     State state("examples/42Ca_deformed_1x11.msg.gz");
//     MultipoleOperators multipoleOperators(state);
//
//     double err = 1e-08;
//
//     // ALL_OUT;
//     // INFO("%14.10f", multipoleOperators.qlm(0, 0));
//     // INFO("%14.10f", multipoleOperators.qlm(1, 0));
//     // INFO("%14.10f", multipoleOperators.qlm(2, 0));
//     // INFO("%14.10f", multipoleOperators.qlm(3, 0));
//     // INFO("%14.10f", multipoleOperators.qlm(4, 0));
//     // INFO("%14.10f", multipoleOperators.qlm(0, 1));
//     // INFO("%14.10f", multipoleOperators.qlm(1, 1));
//     // INFO("%14.10f", multipoleOperators.qlm(2, 1));
//     // INFO("%14.10f", multipoleOperators.qlm(3, 1));
//     // INFO("%14.10f", multipoleOperators.qlm(4, 1));
//     // INFO("%14.10f", multipoleOperators.qlm(0, 2));
//     // INFO("%14.10f", multipoleOperators.qlm(1, 2));
//     // INFO("%14.10f", multipoleOperators.qlm(2, 2));
//     // INFO("%14.10f", multipoleOperators.qlm(3, 2));
//     // INFO("%14.10f", multipoleOperators.qlm(4, 2));
//
//     ASSERT_NEAR(multipoleOperators.qlmObs(0, 0, NEUTRON),   6.2060854344, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(1, 0, NEUTRON),  -0.0000000086, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(2, 0, NEUTRON),   6.3796768665, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(3, 0, NEUTRON),   0.0000016739, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(4, 0, NEUTRON), 137.3177593081, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(0, 0, PROTON ),   5.6418958363, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(1, 0, PROTON ),   0.0000000086, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(2, 0, PROTON ),   3.6203231335, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(3, 0, PROTON ),   0.0000019036, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(4, 0, PROTON ),  40.7764698021, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(0, 0, TOTAL  ),  11.8479812707, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(1, 0, TOTAL  ),  -0.0000000000, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(2, 0, TOTAL  ),  10.0000000000, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(3, 0, TOTAL  ),   0.0000035775, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(4, 0, TOTAL  ), 178.0942291102, err);
//   }
//
//   {
//     // 2ct state
//     State state("examples/42Ca_deformed_2x9.msg.gz");
//     MultipoleOperators multipoleOperators(state);
//
//     double err = 1e-08;
//
//     ASSERT_NEAR(multipoleOperators.qlmObs(0, 0, NEUTRON),  6.2060836786, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(1, 0, NEUTRON), -0.0000001622, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(2, 0, NEUTRON),  6.3539566202, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(3, 0, NEUTRON), -0.0001747522, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(4, 0, NEUTRON), 64.2799824586, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(0, 0, PROTON ),  5.6418958352, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(1, 0, PROTON ),  0.0000001622, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(2, 0, PROTON ),  3.6460433798, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(3, 0, PROTON ), -0.0001754643, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(4, 0, PROTON ), 15.9107568105, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(0, 0, TOTAL  ), 11.8479795138, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(1, 0, TOTAL  ), -0.0000000000, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(2, 0, TOTAL  ), 10.0000000000, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(3, 0, TOTAL  ), -0.0003502165, err);
//     ASSERT_NEAR(multipoleOperators.qlmObs(4, 0, TOTAL  ), 80.1907392691, err);
//   }
// }
//
// //==============================================================================
//
// /*
// TEST(MultipoleOperators, printQlm)
// {
// }
// */
//
// //==============================================================================
//
// /*
// TEST(MultipoleOperators, info)
// {
// }
// */
//
//
//
